### ISSUE TITLE
Pre-release cosmetics

### ISSUE THREAD

**Issue by karel-m** [libtom/libtomcrypt#228]
- [x] 1/ We should remove the old URLs from all `src/*` files ... changing the first comment to ..., c.f. #233 

 - [x] 2/ We should perhaps also replace the old tags `/* $Source$ */ ...` with ..., c.f. #233 

 - [x] 3/ We might want to add a check for 1/ + 2/ to `helper.pl`, c.f. 2cd69fb54109bc48b674d9edf1e326cd57821ab3

 - [x] 4/ https://github.com/libtom/libtomcrypt/issues/228#issuecomment-308953394 - local header files for internal functions, c.f. #241 

 - [x] ~5/ https://github.com/libtom/libtomcrypt/issues/228#issuecomment-309139392 - libtomcrypt.symbols~, c.f. https://github.com/libtom/libtomcrypt/issues/228#issuecomment-310444316

 - [x] 6/ https://github.com/libtom/libtomcrypt/issues/228#issuecomment-309425999 - enforce naming convention `static type _funcname(..)`, c.f. #234 

 - [x] 7/ https://github.com/libtom/libtomcrypt/issues/228#issuecomment-309873479 - ecc_sign+verify_hash_raw API, c.f. #235 

- [x] 8/ https://github.com/libtom/libtomcrypt/issues/228#issuecomment-310313978 - rsa_import_radix, dsa_import_radix, dsa_make_key_ex, c.f. #238 

- [x] 9/ https://github.com/libtom/libtomcrypt/issues/228#issuecomment-311676384 - Fix `make doxygen` warnings #264

**Comment by karel-m** [comment]
Ad 3/ now you can run `./helper.pl -o` (it is not part of `./helper.pl --check-all`)

**Comment by sjaeckel** [comment]
> 1/ We should remove the old URLs from all `src/*` files - which means changing the first comment to:
> ...
> 2/ We should perhaps also replace the old tags `/* $Source$ */ ...` with:

Sure!

Can we use this issue as collection for similar issues? and open separate PR's with changes

**Comment by karel-m** [comment]
> Can we use this issue as collection for similar issues? and open separate PR's with changes

Yes, good idea.

**Comment by sjaeckel** [comment]
4/ We should use local header files for internal functions

**Comment by karel-m** [comment]
> We should use local header files for internal functions

Wouldn't it be enough to simply use:
```C
int some_public_func_a(int a, int b);
int some_public_func_b(int a, int b);
#ifdef LTC_SOURCE
int some_intermal_func_a(int a, int b);
int some_intermal_func_b(int a, int b);
#endif
```

**Comment by rofl0r** [comment]
internal header for internal funcs sounds cleaner to my ears. ppl will end up using stuff in public headers, whether its guarded by a macro or not.

**Comment by sjaeckel** [comment]
> internal header for internal funcs sounds cleaner to my ears. ppl will end up using stuff in public headers, whether its guarded by a macro or not.

very true

> Wouldn't it be enough to simply use:
> ...

before I'd do that I'd go for "internal functions don't have prototypes, define them as extern where you need them"

**Comment by sjaeckel** [comment]
5/ we should create a `libtomcrypt.symbols` file like [libtfm.symbols](https://github.com/libtom/tomsfastmath/blob/develop/libtfm.symbols) for tomsfastmath, so at least the libtomcrypt.so doesn't provide the internal API's

**Comment by karel-m** [comment]
Ad internal functions - would it make sense to introduce a naming convention for those internal fuctions like:
* instead of `dh_make_key_internal(..)`
* something like `i_dh_make_key(..)`

**Comment by sjaeckel** [comment]
> Ad internal functions - would it make sense to introduce a naming convention for those internal fuctions like this?

we have already multiples of these approaches... I think it's mildly useful and not really necessary

**Comment by karel-m** [comment]
6/ consistently use naming convention `static type _funcname(..)`

Here is a patch to `helper.pl` which enables static func name check
```diff
--- a/helper.pl
+++ b/helper.pl
@@ -54,6 +54,9 @@ sub check_source {
       push @{$troubles->{unwanted_strcmp}},  $lineno if $file =~ /^src\/.*\.c$/ && $l =~ /\bstrcmp\s*\(/;
       push @{$troubles->{unwanted_clock}},   $lineno if $file =~ /^src\/.*\.c$/ && $l =~ /\bclock\s*\(/;
       push @{$troubles->{unwanted_qsort}},   $lineno if $file =~ /^src\/.*\.c$/ && $l =~ /\bqsort\s*\(/;
+      if ($file =~ m|src/.*\.c$| && $file !~ m|src/math/.+_desc.c$| && $l =~ /^static\s+\S+\s+([^_][a-zA-Z0-9_]+)\s*\(/) {
+        push @{$troubles->{staticfunc_name}}, "$lineno($1)";
+      }
       $lineno++;
     }
     for my $k (sort keys %$troubles) {
```

Currently mis-named static functions (not stating with `_`):
```
$ ./helper.pl -a
[staticfunc_name] src/ciphers/aes/aes.c line:94(setup_mix),104(setup_mix2)
[staticfunc_name] src/ciphers/anubis.c line:1039(anubis_crypt)
[staticfunc_name] src/ciphers/camellia.c line:198(rot_128)
[staticfunc_name] src/ciphers/des.c line:1301(cookey),1306(deskey),1356(deskey),1366(cookey),1392(cookey),1400(desfunc),1514(desfunc)
[staticfunc_name] src/ciphers/kasumi.c line:39(FI),101(FO),125(FL)
[staticfunc_name] src/ciphers/khazad.c line:677(khazad_crypt)
[staticfunc_name] src/ciphers/kseed.c line:241(rounds)
[staticfunc_name] src/ciphers/multi2.c line:20(pi1),25(pi2),34(pi3),46(pi4),54(setup),82(encrypt),94(decrypt)
[staticfunc_name] src/ciphers/safer/safer.c line:108(Safer_Expand_Userkey),170(Safer_Expand_Userkey)
[staticfunc_name] src/ciphers/skipjack.c line:112(g_func),124(ig_func)
[staticfunc_name] src/ciphers/twofish/twofish.c line:92(sbox),129(sbox),141(gf_mult),164(mds_column_mult),205(mds_mult),217(rs_mult),228(rs_mult),242(h_func),291(g_func),322(g_func)
[staticfunc_name] src/encauth/gcm/gcm_gf_mult.c line:63(gcm_rightshift)
[staticfunc_name] src/hashes/blake2b.c line:156(blake2b_set_lastnode),159(blake2b_is_lastblock),161(blake2b_set_lastblock),169(blake2b_increment_counter),175(blake2b_init0),185(blake2b_init_param),275(blake2b_compress),322(blake2b_compress)
[staticfunc_name] src/hashes/blake2s.c line:148(blake2s_set_lastnode),151(blake2s_is_lastblock),153(blake2s_set_lastblock),161(blake2s_increment_counter),167(blake2s_init0),179(blake2s_init_param),267(blake2s_compress),310(blake2s_compress)
[staticfunc_name] src/hashes/chc/chc.c line:132(chc_compress)
[staticfunc_name] src/hashes/md2.c line:60(md2_update_chksum),74(md2_compress)
[staticfunc_name] src/hashes/md4.c line:78(md4_compress),160(md4_compress)
[staticfunc_name] src/hashes/md5.c line:103(md5_compress),219(md5_compress)
[staticfunc_name] src/hashes/rmd128.c line:86(rmd128_compress),258(rmd128_compress)
[staticfunc_name] src/hashes/rmd160.c line:106(rmd160_compress),316(rmd160_compress)
[staticfunc_name] src/hashes/rmd256.c line:80(rmd256_compress),267(rmd256_compress)
[staticfunc_name] src/hashes/rmd320.c line:101(rmd320_compress),330(rmd320_compress)
[staticfunc_name] src/hashes/sha1.c line:47(sha1_compress),151(sha1_compress)
[staticfunc_name] src/hashes/sha2/sha256.c line:71(sha256_compress),192(sha256_compress)
[staticfunc_name] src/hashes/sha2/sha512.c line:96(sha512_compress),161(sha512_compress)
[staticfunc_name] src/hashes/sha3.c line:102(keccakf)
[staticfunc_name] src/hashes/tiger.c line:579(pass),592(key_schedule),615(tiger_compress),644(tiger_compress)
[staticfunc_name] src/hashes/whirl/whirl.c line:60(whirlpool_compress),114(whirlpool_compress)
[staticfunc_name] src/mac/pelican/pelican.c line:56(four_rounds)
[staticfunc_name] src/math/fp/ltc_ecc_fp_mulmod.c line:577(find_hole),613(find_base),631(add_entry),673(build_lut),780(accel_fp_mul),903(accel_fp_mul2add),1295(ltc_ecc_fp_free_cache)
[staticfunc_name] src/modes/xts/xts_decrypt.c line:19(tweak_uncrypt)
[staticfunc_name] src/modes/xts/xts_encrypt.c line:19(tweak_crypt)
[staticfunc_name] src/pk/asn1/der/generalizedtime/der_decode_generalizedtime.c line:21(char_to_int)
[staticfunc_name] src/pk/asn1/der/sequence/der_decode_sequence_flexi.c line:56(new_element)
[staticfunc_name] src/pk/asn1/der/set/der_encode_set.c line:21(ltc_to_asn1),50(qsort_helper)
[staticfunc_name] src/pk/asn1/der/set/der_encode_setof.c line:25(qsort_helper)
[staticfunc_name] src/pk/asn1/der/utctime/der_decode_utctime.c line:20(char_to_int)
[staticfunc_name] src/pk/dsa/dsa_make_key.c line:31(dsa_make_params)
[staticfunc_name] src/pk/ecc/ecc_import.c line:26(is_point)
[staticfunc_name] src/prngs/fortuna.c line:52(fortuna_update_iv),65(fortuna_reseed)
[staticfunc_name] src/stream/sober128/sober128.c line:33(BYTE2WORD),40(XORWORD),58(cycle),83(nltap),92(s128_savestate),102(s128_reloadstate),113(s128_genkonst),134(s128_diffuse)
check-source:    FAIL 41
```

**Comment by sjaeckel** [comment]
I'll include that in the next clean-up run

**Comment by karel-m** [comment]
7/ remove ecc_sign_hash_raw + ecc_verify_hash_raw from public API

These two were not part of 1.17 and are not part of my ECC enhancements. The main problem is that these function exposes direct pointers to bignum structures (see `*r` + `*s` below), which no other public libtomcrypt functions do.

I mean to remove them from `tomcrypt_pk.h` + make them `static`

```C
int ecc_sign_hash_raw(const unsigned char *in, unsigned long inlen,
                      void *r, void *s,
                      prng_state *prng, int wprng, ecc_key *key);

int ecc_verify_hash_raw(void *r, void *s,
                        const unsigned char *hash, unsigned long hashlen,
                        int *stat, ecc_key *key);
```

**Comment by sjaeckel** [comment]
> 7/ remove ecc_sign_hash_raw + ecc_verify_hash_raw from public API

those were added in #69 by OP-TEE and should remain in the API resp. we'll have to find an alternative(proper) way, c.f. [tee_ltc_provider.c:1764](https://github.com/OP-TEE/optee_os/blob/fe8f79d76694de4d94f957c0d1cf8f60984146c7/core/lib/libtomcrypt/src/tee_ltc_provider.c#L1764) resp. [tee_ltc_provider.c:1821](https://github.com/OP-TEE/optee_os/blob/fe8f79d76694de4d94f957c0d1cf8f60984146c7/core/lib/libtomcrypt/src/tee_ltc_provider.c#L1821)

you're right that it isn't clean to pass a bignum through the API, _but_ it has the advantage that you don't need a length parameter...

I'd propose the following API, so we take care of (de-)serialization of the MPI's internally which is currently done in the `tee_ltc_provider`
```
int ecc_sign_hash_raw(const unsigned char *in, unsigned long inlen,
                      unsigned char *r, unsigned long rlen,
                      unsigned char *s, unsigned long slen,
                      prng_state *prng, int wprng, ecc_key *key);

int ecc_verify_hash_raw(const unsigned char *r, unsigned long rlen,
                        const unsigned char *s, unsigned long slen,
                        const unsigned char *hash, unsigned long hashlen,
                        int *stat, ecc_key *key);
```
@karel-m does that make sense?

@jforissier okay or will you stay on your fork anyway?

**Comment by karel-m** [comment]
Oh, I see. For this use case I have in my `miko-ecc-enhancements`: 
```C
int ecc_sign_hash_rfc7518(const unsigned char *in,  unsigned long inlen,
                                unsigned char *out, unsigned long *outlen,
                                prng_state *prng, int wprng, ecc_key *key);

int ecc_verify_hash_rfc7518(const unsigned char *sig,  unsigned long siglen,
                            const unsigned char *hash, unsigned long hashlen,
                            int *stat, ecc_key *key);
```
Which implements https://tools.ietf.org/html/rfc7518#section-3.4 - e.g.
```
The ECDSA P-256 SHA-256 digital signature is generated as follows:

   1.  Generate a digital signature of the JWS Signing Input using ECDSA
       P-256 SHA-256 with the desired private key.  The output will be
       the pair (R, S), where R and S are 256-bit unsigned integers.
   2.  Turn R and S into octet sequences in big-endian order, with each
       array being be 32 octets long.  The octet sequence
       representations MUST NOT be shortened to omit any leading zero
       octets contained in the values.
   3.  Concatenate the two octet sequences in the order R and then S.
       (Note that many ECDSA implementations will directly produce this
       concatenation as their output.)
   4.  The resulting 64-octet sequence is the JWS Signature value.
```

The implementation is:
* https://github.com/libtom/libtomcrypt/blob/miko-ecc-enhancements/src/pk/ecc/ecc_sign_hash.c#L97
* https://github.com/libtom/libtomcrypt/blob/miko-ecc-enhancements/src/pk/ecc/ecc_verify_hash.c#L57

**Comment by sjaeckel** [comment]
> Oh, I see. For this use case I have in my miko-ecc-enhancements:

oh cool! would it make sense to back-port these functions instead?

**Comment by karel-m** [comment]
> would it make sense to back-port these functions instead?

see #235

**Comment by karel-m** [comment]
8/ API decision about rsa_import_radix, dsa_import_radix, dsa_make_key_ex

see https://github.com/libtom/libtomcrypt/pull/227#issuecomment-309674046

**Comment by sjaeckel** [comment]
I just thought about pushing 4/ and 5/ to `next` as there are already way too much internals exposed...

**Comment by karel-m** [comment]
I agree with leaving out 5/

As for the 4/ we can temporarily "hide" internal functions by `#ifdef LTC_SOURCE ...`

**Comment by jforissier** [comment]
@sjaeckel sorry for the late reply... Anyway, regarding:

> 7/ remove ecc_sign_hash_raw + ecc_verify_hash_raw from public API

I'm fine with @karel-m's proposal, i.e. `ecc_sign_hash_rfc7518()`/`ecc_verify_hash_rfc7518()`. For OP-TEE we will stay on our own fork of LibTomCrypt, but I can confirm the new function work fine for us (they pass our regression tests at least!), so that won't be an issue when we sync up with upstream.

Thanks for the heads-up!

**Comment by sjaeckel** [comment]
9/ Fix `make doxygen` warnings

When creating the doxy documentation there is a huge bunch of warning, they should be fixed.

**Comment by karel-m** [comment]
@sjaeckel can we close this one? There is IMO nothing left (the incomplete doc update is a separate PR).
